/*
 * This file is generated by jOOQ.
 */
package pl.destino.edgetree.db.tables.records


import org.jooq.impl.TableRecordImpl

import pl.destino.edgetree.db.tables.Edge


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class EdgeRecord() : TableRecordImpl<EdgeRecord>(Edge.EDGE) {

    open var fromId: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var toId: Int?
        set(value): Unit = set(1, value)
        get(): Int? = get(1) as Int?

    /**
     * Create a detached, initialised EdgeRecord
     */
    constructor(fromId: Int? = null, toId: Int? = null): this() {
        this.fromId = fromId
        this.toId = toId
        resetChangedOnNotNull()
    }
}
