/*
 * This file is generated by jOOQ.
 */
package pl.destino.edgetree.db.tables.references


import pl.destino.edgetree.db.tables.Edge



/**
 * The table <code>public.edge</code>.
 */
val EDGE: Edge = Edge.EDGE
